server:
  port: 10001
spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://127.0.0.1/blog?serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: true
  jackson:
    date-format: yyyy-MM-dd HH-mm-ss

user:
  auth:
    admin:
      password: #设置栈主认证的密码

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
 # configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
